app/src/main/res/drawable/ic_outline_insert_comment.xml
app/src/main/res/layout/item_board.xml

게시판 아이템 항목 레이아웃 기본 틀을 작성하였습니다.
res/layout/item_board.xml 과 댓글 vector image 추가하였습니다.

issue-4/reservation

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/example/knucseapp/ui/notice/NoticeFragment.kt
app/src/main/java/com/example/knucseapp/ui/reservation/ReservationFragment.kt
app/src/main/res/layout/notice_fragment.xml

[공지사항] webview 사용해서 구현하였습니다.
+ 이전페이지, 다음페이지 버튼 추가
+ 로딩시 progressbar 사용

[#4] add webview to insert notice

---

app/src/main/java/com/example/knucseapp/ui/board/BoardAdapter.kt
app/src/main/java/com/example/knucseapp/ui/board/BoardFragment.kt
app/src/main/java/com/example/knucseapp/ui/board/BoardItem.kt
app/src/main/res/layout/board_fragment.xml
app/src/main/res/layout/board_recycler.xml

[게시판] RecyclerView로 게시글들을 보여줍니다.
- 작성자, 제목, 본문, 날짜, 댓글 수를 표시합니다.
- 제목과 본문은 글이 길어질수록 줄임 표시 처리하였습니다.
- 색상과 폰트는 추후에 수정할 예정입니다.

[#4] set board list layout

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/knucseapp/ui/reservation/ClassRoom.kt
app/src/main/java/com/example/knucseapp/ui/reservation/ReservationActivity.kt
app/src/main/java/com/example/knucseapp/ui/reservation/ReservationAdapter.kt
app/src/main/java/com/example/knucseapp/ui/reservation/ReservationFragment.kt
app/src/main/res/drawable/login_textview_background_shape.xml
app/src/main/res/drawable/select_handler.xml
app/src/main/res/layout/activity_reservation.xml
app/src/main/res/layout/activity_sign_in.xml
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/layout/mypage_recycler.xml
app/src/main/res/layout/notice_fragment.xml
app/src/main/res/layout/reservation_fragment.xml
app/src/main/res/layout/reservation_recycler.xml
app/src/main/res/menu/bottom_nav_item.xml
app/src/main/res/values-round/strings.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/main/res/values/themes.xml

+ Reservation Fragment -> (강의실 클릭) -> Reservation Activity
+ 강의실별 예약 부분은 이후 구현예정
+ layout.xml의 text를 모두 string.xml 에 추가 및 참조하도록 수정
+ AndroidManifest.xml에 지정된 전체 앱 Theme를 @style/Theme.Project로 수정하고 res/themes.xml에서 Theme.Project의 Parent 값을 Theme.MaterialComponents.Light.NoActionBar로 수정
+ 앱 전체 색을 knu_red로 변경

Issue-4 reservation/connect recyclerview with ReservationActivity

---

app/src/main/java/com/example/knucseapp/SignUpActivity.kt
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/main/res/values/themes.xml

+ 회원 가입에 필요한 정보를 추가했습니다.
+ 추가한 정보에 맞게 error 메시지 출력하도록 했습니다.
+ edittext와 error message 글자크기를 더 크게 바꾸었습니다.
+ 인증번호 전송, 인증 확인 버튼의 위치를 각 textview 의 위치와 동일하게 맞추었습니다.

Issue-4 signup/edit signup page

---

app/build.gradle
app/src/main/java/com/example/knucseapp/ui/MainActivity.kt
app/src/main/java/com/example/knucseapp/ui/SignInActivity.kt
app/src/main/java/com/example/knucseapp/ui/SignUpActivity.kt
app/src/main/java/com/example/knucseapp/ui/reservation/ReservationAdapter.kt
app/src/main/java/com/example/knucseapp/ui/reservation/ReservationFragment.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_reservation.xml
app/src/main/res/layout/activity_sign_in.xml
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/layout/board_fragment.xml
app/src/main/res/layout/board_recycler.xml
app/src/main/res/layout/mypage_fragment.xml
app/src/main/res/layout/mypage_recycler.xml
app/src/main/res/layout/notice_fragment.xml
app/src/main/res/layout/reservation_fragment.xml
app/src/main/res/layout/reservation_recycler.xml
app/src/main/res/layout/seat_recycler.xml

+ xml 파일 모두 root layout <layout> 태그로 변경 완료
+ MainActivity, SignInActivity, SignUpActivity 변경 완료
+ Reservation Fragment 변경, viewmodel 연결 완료

Issue-4 reservation/set databinding

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/example/knucseapp/ui/PasswordActivity.kt
app/src/main/java/com/example/knucseapp/ui/SignInActivity.kt
app/src/main/java/com/example/knucseapp/ui/mypage/MyPageAdapter.kt
app/src/main/res/layout/activity_password.xml
app/src/main/res/layout/activity_sign_in.xml
app/src/main/res/values/strings.xml

+ SignIn view에 '비밀번호 찾기' 버튼 추가 
+ 인증번호 확인 버튼 클릭시 새 비밀번호 변경 가능

Issue-4 signin/change login view and add find-password view

---

app/src/main/java/com/example/knucseapp/ui/board/detail/BoardDetailActivity.kt
app/src/main/java/com/example/knucseapp/ui/board/detail/CommentAdapter.kt
app/src/main/java/com/example/knucseapp/ui/board/detail/ReplyAdapter.kt
app/src/main/java/com/example/knucseapp/ui/board/freeboard/BoardAdapter.kt
app/src/main/java/com/example/knucseapp/ui/board/freeboard/BoardDTO.kt
app/src/main/java/com/example/knucseapp/ui/board/freeboard/BoardFragment.kt
app/src/main/java/com/example/knucseapp/ui/board/search/SearchResultFragment.kt
app/src/main/res/drawable/ic_baseline_subdirectory_arrow_right.xml
app/src/main/res/layout/activity_board_detail.xml
app/src/main/res/layout/reply_recycler.xml

- 댓글에 대댓글을 표시할 수 있게 구현했습니다.
- 리사이클러뷰를 중첩시켜 나타내었습니다.
- 리사이클러뷰 position이 상단에 위치하지 않던 문제는 android:descendantFocusability="blocksDescendants" 옵션을 통해 해결하였습니다.

issue-4 reply/대댓글 구현

---

app/src/main/res/layout/activity_write.xml
app/src/main/res/layout/spinner_item.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

+ 카테고리 선택 위치를 toolbar 로 변경시켰습니다.

Issue-4 board/write-add category in toolbar

---

app/src/main/java/com/example/knucseapp/ui/board/freeboard/BoardAdapter.kt
app/src/main/java/com/example/knucseapp/ui/board/freeboard/BoardFragment.kt
app/src/main/res/layout/board_recycler.xml
app/src/main/res/values/strings.xml

- 게시판 레이아웃에서 태그와 프로필이미지를 추가했습니다.
- 뷰 간의 간격을 줄였습니다.

Issue-4 board-layout/add tag and profile

---

app/src/main/java/com/example/knucseapp/ui/SignUpActivity.kt
app/src/main/java/com/example/knucseapp/ui/board/search/SearchActivity.kt
app/src/main/java/com/example/knucseapp/ui/board/search/SearchBlankFragment.kt
app/src/main/java/com/example/knucseapp/ui/board/search/SearchCategoryAdapter.kt
app/src/main/java/com/example/knucseapp/ui/board/search/SearchResultFragment.kt
app/src/main/res/color/test.xml
app/src/main/res/color/test3.xml
app/src/main/res/drawable/search_button_category.xml
app/src/main/res/drawable/search_button_not_selected.xml
app/src/main/res/drawable/search_button_selected.xml
app/src/main/res/layout/search_blank_fragment.xml
app/src/main/res/layout/search_category_recycler.xml
app/src/main/res/values/strings.xml

+ 검색시 카테고리를 설정해 검색할 수 있도록 구현하였습니다.
+ 카테고리는 recycler view를 가로로 사용하여 버튼을 넣었습니다.

Issue-4 search/카테고리검색 구현

---

app/build.gradle
app/proguard-rules.pro
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/knucseapp/ui/mypage/menu/MyGlideApp.kt
app/src/main/java/com/example/knucseapp/ui/mypage/menu/UserInfoEditActivity.kt
app/src/main/res/layout/profile_edit_dialog.xml

- 프로필사진 변경 시, 이미지를 원하는 만큼 잘라서 사용할 수 있습니다.
- image cropper 라이브러리를 활용했습니다.

Issue-4 glide/image cropper 추가

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/example/knucseapp/ui/SignUpActivity.kt
app/src/main/res/drawable/reservation_cancel_button.xml
app/src/main/res/drawable/reservation_confirm_button.xml
app/src/main/res/layout/activity_password.xml
app/src/main/res/layout/activity_password_edit.xml
app/src/main/res/layout/activity_reservation.xml
app/src/main/res/layout/activity_sign_in.xml
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/layout/activity_user_info_edit.xml

+ 필요없는 코드 삭제 완료
+ 모든 버튼 stateanimated = false 로 설정

issue-4 button/버튼 수정

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/example/knucseapp/data/repository/BoardRepository.kt
app/src/main/java/com/example/knucseapp/data/request/BoardService.kt
app/src/main/java/com/example/knucseapp/ui/auth/PasswordActivity.kt
app/src/main/java/com/example/knucseapp/ui/auth/SignUpActivity.kt
app/src/main/java/com/example/knucseapp/ui/board/BoardViewModel.kt
app/src/main/java/com/example/knucseapp/ui/board/detail/BoardDetailActivity.kt
app/src/main/java/com/example/knucseapp/ui/board/detail/CommentActivity.kt
app/src/main/java/com/example/knucseapp/ui/board/detail/CommentAdapter.kt
app/src/main/java/com/example/knucseapp/ui/board/detail/ReplyAdapter.kt
app/src/main/java/com/example/knucseapp/ui/board/freeboard/BoardFragment.kt
app/src/main/java/com/example/knucseapp/ui/board/search/SearchResultFragment.kt
app/src/main/java/com/example/knucseapp/ui/board/writeboard/WriteActivity.kt
app/src/main/java/com/example/knucseapp/ui/mypage/MypageFragment.kt
app/src/main/java/com/example/knucseapp/ui/notice/NoticeFragment.kt
app/src/main/java/com/example/knucseapp/ui/util/ViewUtils.kt
app/src/main/res/layout/activity_board_detail.xml
app/src/main/res/layout/activity_comment.xml
app/src/main/res/values/strings.xml

issue-29 board/대댓글 뷰 추가

---

app/src/main/java/com/example/knucseapp/ui/MainActivity.kt
app/src/main/java/com/example/knucseapp/ui/board/BoardHomeFragment.kt
app/src/main/java/com/example/knucseapp/ui/board/BoardViewModel.kt
app/src/main/java/com/example/knucseapp/ui/board/detail/BoardDetailActivity.kt
app/src/main/java/com/example/knucseapp/ui/board/detail/CommentActivity.kt
app/src/main/java/com/example/knucseapp/ui/board/detail/CommentAdapter.kt
app/src/main/java/com/example/knucseapp/ui/board/detail/ReplyAdapter.kt
app/src/main/java/com/example/knucseapp/ui/board/freeboard/BoardFragment.kt
app/src/main/java/com/example/knucseapp/ui/board/writeboard/WriteActivity.kt
app/src/main/res/layout/activity_comment.xml
app/src/main/res/layout/board_detail_recycler.xml
app/src/main/res/layout/comment_recycler.xml
app/src/main/res/layout/reply_recycler.xml

+ 대댓글 완료
+ 게시글, 댓글 수정 버튼 작성자에게만 보이도록 수정

issue-29 board/대댓글 뷰 구현

---

app/src/main/java/com/example/knucseapp/ui/board/BoardHomeFragment.kt
app/src/main/java/com/example/knucseapp/ui/board/FragmentAdapter.kt
app/src/main/java/com/example/knucseapp/ui/board/detail/BoardDetailActivity.kt
app/src/main/java/com/example/knucseapp/ui/board/freeboard/BoardFragment.kt

#29 
+ 글 쓰기 완료 후 돌아오면 게시글 category tab 으로 이동하고 새로고침 되도록 구현하였습니다.

issue-29 board/글쓰기 후 새로고침 완료

---

app/src/main/java/com/example/knucseapp/data/repository/BoardRepository.kt
app/src/main/java/com/example/knucseapp/data/request/BoardService.kt
app/src/main/java/com/example/knucseapp/ui/board/BoardViewModel.kt
app/src/main/java/com/example/knucseapp/ui/board/search/SearchActivity.kt
app/src/main/java/com/example/knucseapp/ui/board/search/SearchBlankFragment.kt
app/src/main/java/com/example/knucseapp/ui/board/search/SearchCategoryAdapter.kt
app/src/main/java/com/example/knucseapp/ui/board/search/SearchResultFragment.kt
app/src/main/java/com/example/knucseapp/ui/board/search/SearchResultViewModel.kt
app/src/main/res/layout/search_result_fragment.xml
app/src/main/res/values/strings.xml

+ 기존에 검색 뷰에서 카테고리 선택을 검색 범위(내용, 제목, 작성자)로 수정하였습니다.
+ 범위를 필수로 선택한 후 검색어를 입력하여 검색하면 검색 범위에 맞는 결과가 나오도록 하였습니다.

issue-29 board/search

---

app/src/main/java/com/example/knucseapp/ui/mypage/menu/UserInfoEditActivity.kt
app/src/main/java/com/example/knucseapp/ui/reservation/seat/ReservationConfirmActivity.kt
app/src/main/res/layout/activity_reservation_confirm.xml
app/src/main/res/values/strings.xml

- 예약이 완료되면 예약 확인페이지에서 예약정보를 조회합니다.

issue-35 reservation confirm/예약확인

---

app/src/main/java/com/example/knucseapp/data/model/FindReservationDTO.kt
app/src/main/java/com/example/knucseapp/ui/mypage/menu/ReservationHistoryActivity.kt
app/src/main/java/com/example/knucseapp/ui/reservation/seat/ReservationConfirmActivity.kt

- 예약 확인 뷰에서는 입퇴실시간, 예약 내역 뷰에서는 연장횟수 및 입퇴실 시간을 추가했습니다.

issue-35 reservation-confirm/예약확인 및 예약내역 뷰 정보 추가

---

app/src/main/java/com/example/knucseapp/data/repository/ReservationRepository.kt
app/src/main/java/com/example/knucseapp/data/request/ReservationService.kt
app/src/main/java/com/example/knucseapp/ui/mypage/menu/ReservationHistoryActivity.kt
app/src/main/java/com/example/knucseapp/ui/reservation/ReservationViewModel.kt

- 만료 2시간 전부터 예약 연장 가능 / 아닐 시 토스트 메세지로 알림
- 연장 3번부터는 연장하기 버튼 비활성화

issue-35 reservation/예약 연장하기 구현
